### ISSUE TITLE
Nishida is improperly credited as designer of Kamex (Blastoise) whereas she says she designed Kamēru (Wartortle)

### ISSUE THREAD

**Issue by LudwigvonWu** [GFWorks/gfworks.github.io#1]
In the interview you just found (https://web.archive.org/web/19980121112202fw_/http://www.gamefreak.co.jp/POKEMON/INTER/ATSUKO/INTER_AT.HTM) Atsuko Nishida said that she designed Zenigame (Squirtle) and Kamēru (Wartortle), she correctly doesn't state that she designed Kamex (Blastoise) as that design was actually one of the first Capsule Monsters designs (under the name of Caravaggio).

That part should be corrected.

**Comment by GFWorks** [comment]
Thanks - corrected.
